### PR TITLE
Support installation from URLs

### LINKED ISSUE #19: Support pip extensions at arbitrary URLs
The `install.pp` class allows for installation of sentry extensions via `pip`, but only uses the default values for the [python::pip](https://github.com/stankevich/puppet-python#pythonpip) defined type.  If we pass a hash, rather than an array, to the [iterator](https://github.com/covermymeds/puppet-sentry/blob/master/manifests/install.pp#L127), we should be able to accept arbitrary source URLs from which to install.

Several sentry extensions have updated versions on GitHub, but stale versions at PyPI.

### PR DESCRIPTION
**Pull request by skpy**
The primary intent of this PR is to allow installation of Sentry from a URL. This allows Sentry to be installed via `pip` directly from GitHub, rather than PyPI.

It also adds support for installing extensions from URLs, by taking a hash of extensions to install in the format `{extension_name => extension_url}`.

Closes #19

The Sentry team has been moving a lot of configuration from sentry.conf.py to config.yml, so this PR addresses some of those.  See https://docs.getsentry.com/on-premise/server/warnings/  This includes updating the SENTRY_CONF and --config options to point to the Sentry path, rather than a specific config file.

And I've updated most of the Python helper scripts and WSGI file to use virtualenv's [activate_this.py](http://virtualenv.readthedocs.io/en/latest/userguide/#using-virtualenv-without-bin-python) script.

I don't think this PR is **quite** complete: I want to test both fresh installs and upgrades a few more times ot make sure everything is working.  But I want to get this out for review earlier, rather than later.

### CODE REVIEW

**Comment by skpy** [comment]
The `execfile`s are there now.  They weren't part of the commits on which you commented @nchowning.  Double-check, though, please.

**Comment by skpy** [comment]
The [python::pip](https://github.com/stankevich/puppet-python#pythonpip) documentation states that the default is "none".  The [code](https://github.com/stankevich/puppet-python/blob/master/manifests/pip.pp#L71) sets it to `false`.  If we specify `undef` in our invocation, it should fall through to the module's default value, I think.  We could default to `false`, though, to be explicit and conformant with the module's default.

**Comment by nchowning** [comment]
Cool. I think that it would work out in the wash as undef but setting it to false is probably the safer approach. 👍

**Comment by skpy** [comment]
When upgrading, the Celery worker is not fully restarted.  This has the Sentry web interface complaining:

> Celery workers are referencing a different version of Sentry (8.4.1 vs 8.1.2)

**Comment by skpy** [comment]
Rather than have this PR increase any further in scope, I think it's ready to merge.  I'll address the other recently opened issues in a new PR, and then we can cut a new release.

Your thoughts, @nchowning @dansajner ?

**Comment by nchowning** [comment]
@skpy Sounds like a good plan to me!

**Pull request merged**
